# Site settings
title: Line Boost
subtitle: GPL v2 发布的自由的微信游戏
email: 1786762946@qq.com
description: "<a rel='license' href='http://creativecommons.org/licenses/by-sa/4.0/'><img alt='知识共享许可协议' style='border-width:0' src='https://i.creativecommons.org/l/by-sa/4.0/88x31.png' /></a><br />本网站内容均采用<a rel='license' href='http://creativecommons.org/licenses/by-sa/4.0/'>知识共享署名-相同方式共享 4.0 国际许可协议</a>进行许可。"
baseurl: '/LineBoost'
url: 'http://pisces000221.github.io/LineBoost'
githubrepo: 'https://github.com/Pisces000221/LineBoost'
github_username:  Pisces000221

# Build settings
markdown: kramdown
permalink: pretty
